### PR TITLE
Create optimising.rst

### PR DESCRIPTION
**Pull request by jkwok678**
To help people optimize their servers on lower end machines

### CODE REVIEW

**Comment by clrxbl** [comment]
Better idea to just link to https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

**Comment by kickash32** [comment]
Best to keep some documentation about recommended settings because an external guide may not be regularly updated/managed.

**Comment by Chew** [comment]
I agree we should have something like this, however the provided file is very empty! Should list a lot more things, especially from the link @clrxbl linked, obviously modified to fit Paper better.

**Comment by zachbr** [comment]
We are not interested in providing an "official" optimized recommendation like this.

These sorts of optimizations can result in changing game behaviors and it is better for server owners to read and understand these options and make decisions tailored for their server.

**Pull request closed without merging**
