### PR TITLE
Document System Properties

### LINKED ISSUE #23: document system properties
Paper exposes a number of system properties that aren't documented anywhere. Some of these are intentionally only exposed as system properties so that people do not use them- which of these do and do not get documented could be up for discussion.

I grabbed this quick list of what I believe to have been added by paper but I haven't checked this to be correct or verified it is contains all additions. Just leaving it here for myself/whoever wants to document these.
```
paper.playerconnection.keepalive
paper.ticklist-excessive-delay-threshold
timings.bypassMax
LetMeReload
paper.disableChannelLimit
net.kyori.adventure.text.warnWhenLegacyFormattingDetected
Paper.DisableClassPrioritization
Paper.disableFlushConsolidate
Paper.debugDynamicMissingKeys
disable.watchdog
paper.explicit-flush
paper.debug-async-visible-chunks
Paper.enable-sync-chunk-writes
paper.debug-sync-loads
Paper.ignoreWorldDataVersion
Paper.allowAsyncChunksSingleCore
debug.entities
Paper.bypassHostCheck
paper.ticklist-warn-on-excessive-delay
debug.rewriteForIde
convertLegacySigns
Paper.IgnoreJavaVersion
paper.waitforchunks
paper.flush-on-save
disable.book-limits
paper.alwaysPrintWarningState
paper.maxCustomChannelName
Paper.maxSignLength
Paper.FilterThreshhold
Paper.minPrecachedDatafixVersion
paper.maxChunkThreads
Paper.nibbleBucketSize
Paper.maxNibblePoolSize
Paper.WorkerThreadCount
Paper.excessiveTELimit
paper.ticklist-max-tick-delay
printSaveStats
paper.maxChunkThreads
paper.genThreadPriority
paper.loadThreadPriority
```

### LINKED ISSUE #79: document system properties
Paper exposes a number of system properties that aren't documented anywhere. Some of these are intentionally only exposed as system properties so that people do not use them- which of these do and do not get documented could be up for discussion.

I grabbed this quick list of what I believe to have been added by paper but I haven't checked this to be correct or verified it is contains all additions. Just leaving it here for myself/whoever wants to document these.
```
paper.playerconnection.keepalive
paper.ticklist-excessive-delay-threshold
timings.bypassMax
LetMeReload
paper.disableChannelLimit
net.kyori.adventure.text.warnWhenLegacyFormattingDetected
Paper.DisableClassPrioritization
Paper.disableFlushConsolidate
Paper.debugDynamicMissingKeys
disable.watchdog
paper.explicit-flush
paper.debug-async-visible-chunks
Paper.enable-sync-chunk-writes
paper.debug-sync-loads
Paper.ignoreWorldDataVersion
Paper.allowAsyncChunksSingleCore
debug.entities
Paper.bypassHostCheck
paper.ticklist-warn-on-excessive-delay
debug.rewriteForIde
convertLegacySigns
Paper.IgnoreJavaVersion
paper.waitforchunks
paper.flush-on-save
disable.book-limits
paper.alwaysPrintWarningState
paper.maxCustomChannelName
Paper.maxSignLength
Paper.FilterThreshhold
Paper.minPrecachedDatafixVersion
paper.maxChunkThreads
Paper.nibbleBucketSize
Paper.maxNibblePoolSize
Paper.WorkerThreadCount
Paper.excessiveTELimit
paper.ticklist-max-tick-delay
printSaveStats
paper.maxChunkThreads
paper.genThreadPriority
paper.loadThreadPriority
```

### PR DESCRIPTION
**Pull request by e-im**
I've made a small start on this, and now have what I believe to be a complete list. This is still a very early draft with a lot left unfinished however any feedback is appreciated. They also currently aren't in any order bar the order I initially wrote them down in

- [X] paper.playerconnection.keepalive
~~- [X] paper.ticklist-warn-on-excessive-delay~~
~~- [X] paper.ticklist-excessive-delay-threshold~~
~~- [ ] paper.ticklist-max-tick-delay~~
~~- [X] timings.bypassMax~~
- [X] LetMeReload
- [X] paper.disableChannelLimit
- [ ] net.kyori.adventure.text.warnWhenLegacyFormattingDetected ~~-- NOT USED~~ - Part of adventure, not documented here
- [X] Paper.DisableClassPrioritization
~~- [ ] Paper.disableFlushConsolidate~~
- [X] Paper.debugDynamicMissingKeys
- [X] disable.watchdog
~~- [X] paper.explicit-flush~~
~~- [X] paper.debug-async-visible-chunks~~
- [X] Paper.enable-sync-chunk-writes
- [X] paper.debug-sync-loads
- [X] Paper.ignoreWorldDataVersion
~~- [X] Paper.allowAsyncChunksSingleCore~~
- [X] debug.entities
- [X] Paper.bypassHostCheck
~~- [ ] debug.rewriteForIde~~
~~- [ ] convertLegacySigns~~ - [not a paper thing](https://github.com/PaperMC/Paper/blob/3d43c5e50077ac7fa1e68cf7a7add0ac77768a61/patches/server/0309-Don-t-check-ConvertSigns-boolean-every-sign-save.patch)
- [X] Paper.IgnoreJavaVersion
~~- [ ] paper.waitforchunks~~
~~- [ ] paper.flush-on-save~~ - now spigot
~~- [ ] disable.book-limits~~ - removed
- [X] paper.alwaysPrintWarningState
- [X] paper.maxCustomChannelName
- [X] Paper.maxSignLength
~~- [ ] Paper.FilterThreshhold~~
- [X] Paper.minPrecachedDatafixVersion
- [X] paper.maxChunkThreads
~~- [ ] Paper.nibbleBucketSize~~
~~- [ ] Paper.maxNibblePoolSize~~
- [X] Paper.WorkerThreadCount
- [X] Paper.excessiveTELimit
- [X] printSaveStats
~~- [ ] paper.genThreadPriority~~ removed
~~- [ ] paper.loadThreadPriority~~ removed

Closes PaperMC/docs#23

### CODE REVIEW

**Comment by kezz** [comment]
`net.kyori.adventure.text.warnWhenLegacyFormattingDetected` is used in Adventure, so the system property still works okay.

One other minor thing of note, are there some of these properties that should remain undocumented? For example, it seems like a bad idea to document the properties to ignore Java and world versions as they should never really be used. People might have errors/warning and then find these docs and just hide them rather than fixing the problem. Not sure if that should be encouraged?

**Comment by Chew** [comment]
That should be discussed in PaperMC/docs#23

**Comment by sulu5890** [comment]
I do agree that some of these should not be documented, however both that you mentioned, while they can cause harm, are in the pins of #paper-help and note infrequently used. Instead I've taken the approach of not documenting ones that I could not come up with a reasonable use for, or that you could only have a use for if you were already looking at the patch where they were added.

I'm a bit unsure of what to do with stuff from adventure, whether that should be documented here or there as it's not paper specific. I only found `net.kyori.adventure.text.warnWhenLegacyFormattingDetected` because it was included in the adventure patch, but it's use there had been disabled. The same goes for spigot/craftbukkit, as I can't find that they are documented anywhere either.

**Review by Proximyst — CHANGES_REQUESTED** [review]

**Comment by e-im** [comment]
I'll continue this at some point, including stuff paper didn't add at https://github.com/PaperMC/docs. if someone else wants to pick this up feel free.

**Pull request closed without merging**
